apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: {{ .Values.deployment1.replicaCount }}
  selector:
    matchLabels:
      app: deployment1
  template:
    metadata:
      labels:
        app: deployment1
    spec:
      containers:
        - name: deployment1
          image: {{ .Values.deployment1.image }}
          ports:
            - containerPort: 80
